name: Upload Google Credentials

on:
  workflow_dispatch:

jobs:
  upload-credentials:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
      
    - name: 'Create credentials file'
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > google_credentials.json
        
    - name: 'Deploy credentials to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: 'simple-amazon-sync'
        package: '.'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
